const games = [
  {
    id: 'guess-the-flag',
    title: 'Guess the Flag',
    description: 'See the flag, name the country.',
    icon: 'flag',
    category: 'geography',
    path: '/games/guess-the-flag',
    playPath: '/play/guess-the-flag',
    apiEndpoint: '/api/questions/flags',
    available: true,
  },
  {
    id: 'guess-the-capital',
    title: 'Guess the Capital',
    description: 'What is the capital of this country?',
    icon: 'building-bank',
    category: 'geography',
    path: '/games/guess-the-capital',
    playPath: '/play/guess-the-capital',
    apiEndpoint: '/api/questions/capitals',
    available: true,
  },
  {
    id: 'guess-the-map-country',
    title: 'Guess the Country',
    description: 'Identify the highlighted country on the map.',
    icon: 'map-2',
    category: 'geography',
    path: '/games/guess-the-map-country',
    playPath: '/play/guess-the-map-country',
    apiEndpoint: '/api/questions/map-location',
    available: true,
  },
  {
    id: 'guess-the-currency',
    title: 'Guess the Currency',
    description: 'What currency does this country use?',
    icon: 'coin',
    category: 'geography',
    path: '/games/guess-the-currency',
    playPath: '/play/guess-the-currency',
    apiEndpoint: '/api/questions/currencies',
    available: true,
  },
];

export default games;